name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg API_BASE_URL=${{ secrets.PROD_API_URL }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/caas-tc-fe:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/caas-tc-fe:${{ github.sha }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: caas-tc-fe
          resourceGroup: caas_tc
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/caas-tc-fe:${{ github.sha }}